### ISSUE TITLE
Fix Translate Button

### ISSUE THREAD

**Issue by rkishan516** [NJACKWinterOfCode/SpacerTranslator#2]
`Translate` Button is not working properly

**Comment by Vaishakh-SM** [comment]
Please could you guide me on how to fix this?

**Comment by rkishan516** [comment]
Ya, when you write something and hit translate button, it doesn't show output but if you again tap on that now it will. You have to make it on single tap.

**Comment by rkishan516** [comment]
@Vaishakh-SM are you working on this?
